-- === #151 stage 2: a role carries a site permission matrix, not just instance powers ===
-- The three JSON columns are the matrix: what a holder may do on a site, what an MCP client acting
-- as them may do, and what a key they issued may do. The last two are subsets of the first, which
-- is enforced in @hedge/core rather than here.
ALTER TABLE `roles` ADD `site_permissions` text DEFAULT '[]' NOT NULL;--> statement-breakpoint
ALTER TABLE `roles` ADD `mcp_permissions` text DEFAULT '[]' NOT NULL;--> statement-breakpoint
ALTER TABLE `roles` ADD `api_key_permissions` text DEFAULT '[]' NOT NULL;--> statement-breakpoint
-- === Seed the three built-in roles as rows, so their matrices become editable ===
-- Every existing site_users row keeps its slug, so these sets decide what everybody holding
-- admin, editor or viewer can do the moment this lands. They restate exactly what the rank-based
-- checks granted the day before, permission by permission, and packages/core pins that.
-- The instance permissions column stays empty on purpose: for a built-in slug those are read from
-- code, where they cannot be edited and cannot lock an owner out. Only the site half is a row.
-- OR IGNORE because a deployment that somehow already holds one of these slugs keeps what it has.
INSERT OR IGNORE INTO `roles` (`id`, `slug`, `name`, `description`, `permissions`, `site_permissions`, `mcp_permissions`, `api_key_permissions`, `default_site_role`, `created_at`, `updated_at`)
VALUES ('rol_builtin_admin', 'admin', 'Admin', 'Runs the deployment — users, sites, email and roles — and reaches every site.', '[]', '["entries:create","entries:read","entries:update","entries:delete","media:create","media:read","media:update","media:delete","collections:create","collections:read","collections:update","collections:delete","newsletters:create","newsletters:read","newsletters:update","newsletters:delete","newsletters:send","subscribers:create","subscribers:read","subscribers:update","subscribers:delete","members:create","members:read","members:update","members:delete","api_keys:create","api_keys:read","api_keys:update","api_keys:delete","analytics:read"]', '["entries:create","entries:read","entries:update","entries:delete","media:create","media:read","media:update","media:delete","collections:create","collections:read","collections:update","collections:delete","newsletters:create","newsletters:read","newsletters:update","newsletters:delete","newsletters:send","subscribers:create","subscribers:read","subscribers:update","subscribers:delete","members:create","members:read","members:update","members:delete","api_keys:create","api_keys:read","api_keys:update","api_keys:delete","analytics:read"]', '["entries:create","entries:read","entries:update","entries:delete","media:create","media:read","media:update","media:delete","collections:create","collections:read","collections:update","collections:delete","newsletters:create","newsletters:read","newsletters:update","newsletters:delete","newsletters:send","subscribers:create","subscribers:read","subscribers:update","subscribers:delete","members:create","members:read","members:update","members:delete","api_keys:create","api_keys:read","api_keys:update","api_keys:delete","analytics:read"]', NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
--> statement-breakpoint
INSERT OR IGNORE INTO `roles` (`id`, `slug`, `name`, `description`, `permissions`, `site_permissions`, `mcp_permissions`, `api_key_permissions`, `default_site_role`, `created_at`, `updated_at`)
VALUES ('rol_builtin_editor', 'editor', 'Editor', 'Writes content on the sites they are granted access to.', '[]', '["entries:create","entries:read","entries:update","entries:delete","media:create","media:read","media:update","media:delete","collections:read","newsletters:create","newsletters:read","newsletters:update","newsletters:delete","subscribers:create","subscribers:read","subscribers:update","subscribers:delete","members:read","analytics:read"]', '["entries:create","entries:read","entries:update","entries:delete","media:create","media:read","media:update","media:delete","collections:read","newsletters:create","newsletters:read","newsletters:update","newsletters:delete","subscribers:create","subscribers:read","subscribers:update","subscribers:delete","members:read","analytics:read"]', '["entries:create","entries:read","entries:update","entries:delete","media:create","media:read","media:update","media:delete","collections:read","newsletters:create","newsletters:read","newsletters:update","newsletters:delete","subscribers:create","subscribers:read","subscribers:update","subscribers:delete","members:read","analytics:read"]', 'editor', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
--> statement-breakpoint
INSERT OR IGNORE INTO `roles` (`id`, `slug`, `name`, `description`, `permissions`, `site_permissions`, `mcp_permissions`, `api_key_permissions`, `default_site_role`, `created_at`, `updated_at`)
VALUES ('rol_builtin_viewer', 'viewer', 'Viewer', 'Reads content on the sites they are granted access to.', '[]', '["entries:read","media:read","collections:read","analytics:read"]', '["entries:read","media:read","collections:read","analytics:read"]', '["entries:read","media:read","collections:read","analytics:read"]', 'viewer', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
